[package]
name = "serdo-ron-test"
version = "0.1.0"
authors = ["lsy <aresli96@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
ron = "0.6.0"