[package]
name = "meow"
version = "0.1.0"
authors = ["lsy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dotenv_codegen = "0.15.0"
clap = { version = "2.33.1", features = ["yaml"]}
